language: go

services:
  - docker

branches:
  only:
    - master

# build container
before_install:
  - docker build -t andymender/linuxmender-go
  # run tests
  # - docker run -p 8080:8080 andymender/linuxmender-go test

# TODO: add SSH access to deployment machine and `git clone && git pull`?
script:
  - echo "Build successful :)"
