version: '3.3'

services:
  # main Web app
  app:
    network_mode: "host"

    environment:
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_PORT: $DATABASE_PORT

    build:
      context: .
      dockerfile: app.Dockerfile
    
    restart: always

    ports:
      - "8080:8080"

    command: app

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    
    # depends_on:
    #   - redis
  
#   # db for dynamic data
#   redis:
#     network_mode: "host"
#     image: "redis:5"
#     configs:
#       - source: redis_config
#         target: /etc/redis.conf
#         uid: "969"
#         gid: "969"
#         mode: 0440
    
#     ports:
#       - "6379:6579"
     
#     logging:
#       driver: "json-file"
#       options:
#         max-size: "10m"
#         max-file: "5"

# configs:
#   redis_config:
#     file: /usr/local/share/redis/redis.conf
